server:
  port: 9002
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      timeout: 120m

spring:
  jpa:
    database: oracle
  datasource:

    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.160.7.151:1521/hrmis
    username: srpm
    password: srpm@2021
    druid:
      initial-size: 10
      minIdle: 10
      maxActive: 20
      maxWait: 30000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20

#    filters: stat,wall,slf4j

#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

    #useGlobalDataSourceStat: true
  servlet:
      multipart:

        enabled: true

        max-file-size: 20MB

        max-request-size: 100MB

#  devtools:
#    restart:
#      enabled: true
#      additional-paths: src/main/java
#      exclude: WEB-INF/**

mybatis:

  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gt.srpm.admin.entity


#quartz:
#  enabled: false


logging:
  level:
    com.oa.contacts.admin.dao: debug
  file:
    path: src\main\resources\logger\


pagehelper:
  helper-dialect: oracle
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  pageSizeZero: true


fdfs:
  so-timeout: 1501
  connect-timeout: 2000
  thumb-image:
    width: 150
    height: 150
  tracker-list:
    - 10.160.7.153:23002
